version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./mongodb/codigos_dtc.csv:/codigos_dtc.csv
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongodb

    

#  servidor:
#    build:
#      context: ./nextjs
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./nextjs:/app
#    depends_on:
#        - mongodb


